- Improve libutil detection. Systems that have both ptsname() and   openpty() does not need libutil, this change (probably) covers   these systems. Based on patch by 1xx ([freewnn-users 133]).
- Some cosmetic fixes.


git-svn-id: file:///home/mitsutoshi/src/sourceforge.jp/rsync/svn/trunk@260 62ffc7d7-c204-4b8a-a13a-9c32274df18a

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2753,7 +2753,7 @@ case $host in
       if test $GCC = yes; then
         CCOPTIONS="-Dsun -D`uname -p` -DSVR4 -DSYSV"
       else
-        # TODO: need change for sparcv9 / x64 architecture ...
+	# TODO: need change for sparcv9 / x64 architecture ...
         CCOPTIONS="-Xc -xF -xcg92 -Dsun -D`uname -p` -DSVR4 -DSYSV"
       fi
     ;;
@@ -18738,10 +18738,8 @@ fi
 echo "$as_me:$LINENO: result: $ac_cv_lib_util_openpty" >&5
 echo "${ECHO_T}$ac_cv_lib_util_openpty" >&6
 if test $ac_cv_lib_util_openpty = yes; then
-  UUM_LIBS="$UUM_LIBS -lutil"
+  HAVE_LIBUTIL='have_libutil'
 fi
-
-
 
 
 echo "$as_me:$LINENO: checking for ANSI C header files" >&5
@@ -20095,6 +20093,12 @@ _ACEOF
 fi
 
 
+olibs="$LIBS"
+if test "x$HAVE_LIBUTIL" = "xhave_libutil"; then
+    # openpty needs libutil in AC_CHECK_FUNCS, so add temporally
+    LIBS="$LIBS -lutil"
+fi
+
 
 
 
@@ -20285,6 +20289,7 @@ _ACEOF
 fi
 done
 
+LIBS="${olibs}"
 
 JS_SUPPORTOBJS=
 
@@ -20406,6 +20411,101 @@ echo "${ECHO_T}yes" >&6
     echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
   fi
+fi
+
+if test $client = true; then
+
+for ac_func in ptsname
+do
+as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
+echo "$as_me:$LINENO: checking for $ac_func" >&5
+echo $ECHO_N "checking for $ac_func... $ECHO_C" >&6
+if eval "test \"\${$as_ac_var+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+/* System header to define __stub macros and hopefully few prototypes,
+    which can conflict with char $ac_func (); below.  */
+#include <assert.h>
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char $ac_func ();
+char (*f) ();
+
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+/* The GNU C library defines this for functions which it implements
+    to always fail with ENOSYS.  Some functions are actually named
+    something starting with __ and the normal name is an alias.  */
+#if defined (__stub_$ac_func) || defined (__stub___$ac_func)
+choke me
+#else
+f = $ac_func;
+#endif
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  eval "$as_ac_var=yes"
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+eval "$as_ac_var=no"
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_var'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_var'}'`" >&6
+if test `eval echo '${'$as_ac_var'}'` = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define `echo "HAVE_$ac_func" | $as_tr_cpp` 1
+_ACEOF
+ HAVE_PTSNAME='have_ptsname'
+fi
+done
+
+  echo "$as_me:$LINENO: checking whether we use libutil for uum" >&5
+echo $ECHO_N "checking whether we use libutil for uum... $ECHO_C" >&6
+  case "x$HAVE_PTSNAME$HAVE_LIBUTIL" in
+  # 'xhave_ptsnamehave_libutil') ;;
+  # 'xhave_ptsname') ;;
+  'xhave_libutil')
+    echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+    UUM_LIBS="$UUM_LIBS -lutil" ;;
+  # 'x') ;;
+  *)
+    echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+    ;;
+  esac
+
 fi
 
 if test $client = true; then
@@ -21348,11 +21448,11 @@ s,@ac_ct_F77@,$ac_ct_F77,;t t
 s,@LIBTOOL@,$LIBTOOL,;t t
 s,@LIBTOOL_DEPS@,$LIBTOOL_DEPS,;t t
 s,@LIBTOOL_MOD@,$LIBTOOL_MOD,;t t
-s,@UUM_LIBS@,$UUM_LIBS,;t t
 s,@TERMLIB@,$TERMLIB,;t t
 s,@CNVFILE_SUBDIR@,$CNVFILE_SUBDIR,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@JS_SUPPORTOBJS@,$JS_SUPPORTOBJS,;t t
+s,@UUM_LIBS@,$UUM_LIBS,;t t
 s,@INSTUUMFLAGS@,$INSTUUMFLAGS,;t t
 s,@UUMOWNER@,$UUMOWNER,;t t
 s,@UUMGROUP@,$UUMGROUP,;t t
