This commit was manufactured by cvs2svn to create tag 'freewnn-1-1-1-a004'.
git-svn-id: file:///home/mitsutoshi/src/sourceforge.jp/rsync/svn/tags/freewnn-1-1-1-a004@15 62ffc7d7-c204-4b8a-a13a-9c32274df18a

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -1,5 +1,5 @@
 dnl
-dnl $Id: configure.in,v 1.1.1.1 2000-01-16 05:10:44 ura Exp $
+dnl $Id: configure.in,v 1.5 2000-01-16 06:37:13 ura Exp $
 dnl
 
 dnl FreeWnn is a network-extensible Kana-to-Kanji conversion system.
@@ -33,10 +33,26 @@ dnl
 dnl Last modified date: 22,Mar.1999
 dnl
 
+
 dnl
 dnl Process this file with autoconf to produce a configure script.
 dnl
 AC_INIT(Wnn/conv/cvt_head.h)
+
+dnl
+dnl srcdir の絶対パスバージョンの作成。本当はこんなものを定義しなくても
+dnl 動くように Makefile.in を書くべきである。ちょっとずつそうなるように
+dnl 直していきたい
+dnl
+case "$top_srcdir" in
+  .)  abs_top_srcdir=`pwd` ;;
+  /*) abs_top_srcdir=top_srcdir;;
+  *) # Relative path.
+    abs_top_srcdir=`pwd`$ac_dots$ac_given_srcdir ;;
+esac
+AC_SUBST(abs_top_srcdir)
+
+
 
 dnl
 dnl Checks for cc and cpp.
@@ -54,23 +70,88 @@ case $hosttype in
         CPP=/lib/cpp
     fi
     ;;
-"FreeBSD")
+"FreeBSD"|"NetBSD"|"OpenBSD")
     CCOPTIONS="-DCSRG_BASED"
     CDEBUGFLAGS="-O2 -fno-strength-reduce"
     if test -x /usr/libexec/cpp; then
         CPP=/usr/libexec/cpp
     fi
     ;;
+"BSD/OS")
+    CCOPTIONS="-DCSRG_BASED"
+    CDEBUGFLAGS="-O2 -fno-strength-reduce"
+    if test -x /usr/bin/cpp; then
+        CPP=/usr/bin/cpp
+    fi
+    ;;
 "SunOS")
+    case `uname -r` in
+    4.*)
+      if test $CC = gcc; then
+        CDEBUGFLAGS=-O2
+	CCOPTIONS="-Dsun -Dsparc"
+      else
+        CDEBUGFLAGS=-O4
+        CCOPTIONS=""
+      fi
+      CPP=/usr/lib/cpp
+      ;;
+    5.*)
+      if test $CC = gcc; then
+          CDEBUGFLAGS=-O2
+          CCOPTIONS="-Dsun -Dsparc -DSVR4 -DSYSV"
+      else
+          CCOPTIONS="-Xc -xF -xcg92 -Dsun -Dsparc -DSVR4 -DSYSV"
+      fi
+      if test -x /usr/ccs/lib/cpp; then
+          CPP=/usr/ccs/lib/cpp
+      fi
+      ;;
+    *)
+      AC_MSG_ERROR("This system is not supported.")
+      ;;
+    esac
+    ;;
+"HP-UX")
     if test $CC = gcc; then
         CDEBUGFLAGS=-O2
-        CCOPTIONS="-Dsun -Dsparc -DSVR4 -DSYSV"
+        CCOPTIONS="-Dhpux -DSYSV"
     else
-        CCOPTIONS="-Xc -xF -xcg92 -Dsun -Dsparc -DSVR4 -DSYSV"
+        CCOPTIONS="-Ae -Dhpux -DSYSV"
     fi
-    if test -x /usr/ccs/lib/cpp; then
-        CPP=/usr/ccs/lib/cpp
-    fi
+    case `uname -r` in
+    A.09.*)
+      if test -x /lib/cpp; then
+          CPP=/lib/cpp
+      fi
+      ;;
+    B.10.*|B.11.*)
+      if test -x /opt/langtools/lbin/cpp; then
+          CPP=/opt/langtools/lbin/cpp
+      fi
+      ;;
+    *)
+      AC_MSG_ERROR("This system is not supported.")
+      ;;
+    esac
+    ;;
+"BeOS")
+	case `uname -m` in
+    "BePC")
+	  CCOPTIONS="-DBEOS -D_POSIX_SOURCE -D_BSD_SOURCE"
+	  CDEBUGFLAGS="-O2 -fno-strength-reduce"
+	  if test -x /boot/develop/tools/gnupro/lib/gcc-lib/i586-beos/2.9-beos-980929/cpp; then
+	    CPP=/boot/develop/tools/gnupro/lib/gcc-lib/i586-beos/2.9-beos-980929/cpp
+	  fi
+	;;
+    "BeBox"|"BeMac")
+	  CCOPTIONS="-DBEOS -D_POSIX_SOURCE -D_BSD_SOURCE"
+	  NON_GNU_CPP=/boot/apps/GeekGadgets/bin/cpp
+	;;
+    *)
+      { echo "configure: error: "This system is not supported."" 1>&2; exit 1; }
+      ;;
+    esac
     ;;
 *)
     AC_MSG_ERROR("This system is not supported.")
@@ -83,7 +164,7 @@ dnl Checks for programs.
 dnl
 AC_PROG_YACC
 AC_PROG_LEX
-dnl AC_PROG_INSTALL
+AC_PROG_INSTALL
 AC_PROG_LN_S
 AC_PROG_MAKE_SET
 AC_PROG_RANLIB
@@ -166,6 +247,11 @@ AC_FUNC_WAIT3
 AC_CHECK_FUNCS(gethostname mkdir select socket strtol)
 
 dnl
+dnl
+dnl
+AC_CONFIG_HEADER(config.h)
+
+dnl
 dnl Creating Makefiles.
 dnl
-AC_OUTPUT(Wnn/man/2.env/wnn/Makefile Wnn/pubdic/Makefile cWnn/uum/Makefile cWnn/man/6.jutil/Makefile cWnn/man/Makefile Wnn/man/4.cmd/Makefile kWnn/uum/Makefile cWnn/td/rk/Makefile cWnn/include/Makefile Wnn/jd/rk.vi/Makefile Wnn/jd/Makefile Makefile kWnn/include/Makefile Wnn/ld/Makefile Wnn/man/2.env/dic/Makefile Wnn/man/2.env/Makefile Wnn/man/3.libwnn/Makefile Wnn/man/6.jutil/Makefile Wnn/uum/Makefile cWnn/man/1.intro/Makefile cWnn/conv/Makefile Wnn/jd/rk/Makefile cWnn/td/Makefile Wnn/man/Makefile cWnn/td/rk_z/Makefile kWnn/conv/Makefile cWnn/man/4.cmd/Makefile cWnn/jlib/Makefile Wnn/include/Makefile Wnn/jutil/Makefile kWnn/jlib/Makefile cWnn/cd/rk_z/Makefile cWnn/Makefile cWnn/cdic/Makefile cWnn/man/2.env/Makefile Wnn/man/3.libwnn/js_lib/Makefile Wnn/man/3.libwnn/rk_lib/Makefile Contrib/dic/gerodic/Makefile kWnn/Makefile cWnn/jserver/Makefile kWnn/kdic/Makefile cWnn/tdic/Makefile Wnn/romkan/Makefile cWnn/cd/Makefile cWnn/jutil/Makefile cWnn/romkan/Makefile kWnn/jserver/Makefile Wnn/Makefile Wnn/man/3.libwnn/jl_lib/Makefile kWnn/romkan/Makefile kWnn/jutil/Makefile Pubdic/Makefile Wnn/conv/Makefile cWnn/cd/rk/Makefile cWnn/td/rk_p/Makefile Wnn/jlib.V3/Makefile kWnn/kd/Makefile Wnn/ld/rk/Makefile cWnn/etc/Makefile Wnn/jlib/Makefile Wnn/jserver/Makefile Wnn/wnncons/dic/Makefile cWnn/cd/rk_p/Makefile kWnn/kd/rk/Makefile Wnn/wnncons/Makefile Wnn/man/3.libwnn/misc_lib/Makefile kWnn/etc/Makefile)
+AC_OUTPUT(makerule.mk Wnn/man/2.env/wnn/Makefile Wnn/pubdic/Makefile cWnn/uum/Makefile cWnn/man/6.jutil/Makefile cWnn/man/Makefile Wnn/man/4.cmd/Makefile kWnn/uum/Makefile cWnn/td/rk/Makefile cWnn/include/Makefile Wnn/jd/rk.vi/Makefile Wnn/jd/Makefile Makefile kWnn/include/Makefile Wnn/ld/Makefile Wnn/man/2.env/dic/Makefile Wnn/man/2.env/Makefile Wnn/man/3.libwnn/Makefile Wnn/man/6.jutil/Makefile Wnn/uum/Makefile cWnn/man/1.intro/Makefile cWnn/conv/Makefile Wnn/jd/rk/Makefile cWnn/td/Makefile Wnn/man/Makefile cWnn/td/rk_z/Makefile kWnn/conv/Makefile cWnn/man/4.cmd/Makefile cWnn/jlib/Makefile Wnn/include/Makefile Wnn/jutil/Makefile kWnn/jlib/Makefile cWnn/cd/rk_z/Makefile cWnn/Makefile cWnn/cdic/Makefile cWnn/man/2.env/Makefile Wnn/man/3.libwnn/js_lib/Makefile Wnn/man/3.libwnn/rk_lib/Makefile Contrib/dic/gerodic/Makefile kWnn/Makefile cWnn/jserver/Makefile kWnn/kdic/Makefile cWnn/tdic/Makefile Wnn/romkan/Makefile cWnn/cd/Makefile cWnn/jutil/Makefile cWnn/romkan/Makefile kWnn/jserver/Makefile Wnn/Makefile Wnn/man/3.libwnn/jl_lib/Makefile kWnn/romkan/Makefile kWnn/jutil/Makefile Pubdic/Makefile Wnn/conv/Makefile cWnn/cd/rk/Makefile cWnn/td/rk_p/Makefile Wnn/jlib.V3/Makefile kWnn/kd/Makefile Wnn/ld/rk/Makefile cWnn/etc/Makefile Wnn/jlib/Makefile Wnn/jserver/Makefile Wnn/wnncons/dic/Makefile cWnn/cd/rk_p/Makefile kWnn/kd/rk/Makefile Wnn/wnncons/Makefile Wnn/man/3.libwnn/misc_lib/Makefile kWnn/etc/Makefile)
