Added (first step of) support for new installation path layout. Maybe useful for package managers.  Please note that new layout is disabled by default. You need to specify following configure parameter if you try this.
- Added --enable-traditional-layout (default: yes) parameter to
  configure. If disabled, we install jserver / wnnstat / wnnkill to
  sbindir. Currently this will take effect on program path only.
- Also added --enable-sub-bindir (default: yes if
  --enable-traditional-layout, no otherwise). If disabled, we install
  programs to bindir (/ sbindir) directly (i.e. we don't mkdir Wnn4
  (, cWnn4 and kWnn4) sub directory to bindir (/ sbindir)) .
- Enable --program-transform-name and its family to programs
  (ex. jserver, uum, wnnkill, atod) and corresponding manpages.
- Update INSTALL documentation (Japanese version). English version
  will come later ...
- Strip old mail address (as usual).
- Merged part of my code to build correctly if builddir != srcdir (as
  usual).


git-svn-id: file:///home/mitsutoshi/src/sourceforge.jp/rsync/svn/trunk@248 62ffc7d7-c204-4b8a-a13a-9c32274df18a

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -989,6 +989,11 @@ _ACEOF
 
   cat <<\_ACEOF
 
+Program names:
+  --program-prefix=PREFIX            prepend PREFIX to installed program names
+  --program-suffix=SUFFIX            append SUFFIX to installed program names
+  --program-transform-name=PROGRAM   run sed PROGRAM on installed program names
+
 X features:
   --x-includes=DIR    X include files are in DIR
   --x-libraries=DIR   X library files are in DIR
@@ -1020,6 +1025,8 @@ Optional Features:
   --enable-kWnn           build and install kWnn [default=yes]
   --enable-ipv6           build and install IPv6 [default=no]
   --enable-unsafe-path    allow creating files in an arbitrary path [default=no]
+  --enable-traditional-layout Install files in traditional directories [default=yes]
+  --enable-sub-bindir         Install executables to (ex.) $(bindir)/Wnn4 [default=yes if --enable-traditional-layout, no otherwise]
   --enable-shared[=PKGS]
                           build shared libraries [default=yes]
   --enable-static[=PKGS]
@@ -1512,6 +1519,20 @@ host_os=`echo $ac_cv_host | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\3/'`
 
 
 
+test "$program_prefix" != NONE &&
+  program_transform_name="s,^,$program_prefix,;$program_transform_name"
+# Use a double $ so make ignores it.
+test "$program_suffix" != NONE &&
+  program_transform_name="s,\$,$program_suffix,;$program_transform_name"
+# Double any \ or $.  echo might interpret backslashes.
+# By default was `s,x,x', remove it if useless.
+cat <<\_ACEOF >conftest.sed
+s/[\\$]/&&/g;s/;s,x,x,$//
+_ACEOF
+program_transform_name=`echo $program_transform_name | sed -f conftest.sed`
+rm conftest.sed
+
+
 
 # Check whether --enable-debug or --disable-debug was given.
 if test "${enable_debug+set}" = set; then
@@ -1855,6 +1876,81 @@ cat >>confdefs.h <<\_ACEOF
 #define WNN_ALLOW_UNSAFE_PATH 1
 _ACEOF
 
+fi
+
+# Check whether --enable-traditional-layout or --disable-traditional-layout was given.
+if test "${enable_traditional_layout+set}" = set; then
+  enableval="$enable_traditional_layout"
+  case "${enableval}" in
+   yes) trad_layout=true ;;
+   no)  trad_layout=false ;;
+   *)   { { echo "$as_me:$LINENO: error: bad value for --enable-traditional-layout" >&5
+echo "$as_me: error: bad value for --enable-traditional-layout" >&2;}
+   { (exit 1); exit 1; }; } ;;
+esac
+else
+  trad_layout=true
+fi;
+
+if test $trad_layout = "true"; then
+  WNNSBINDIR="\$(bindir)"
+  # More path settings will come later ...
+else
+  WNNSBINDIR="\$(sbindir)"
+  # Same as above.
+fi
+
+
+# Check whether --enable-sub-bindir or --disable-sub-bindir was given.
+if test "${enable_sub_bindir+set}" = set; then
+  enableval="$enable_sub_bindir"
+  case "${enableval}" in
+   yes) sub_bindir=true ;;
+   no)  sub_bindir=false ;;
+   *)   { { echo "$as_me:$LINENO: error: bad value for --enable-sub-bindir" >&5
+echo "$as_me: error: bad value for --enable-sub-bindir" >&2;}
+   { (exit 1); exit 1; }; } ;;
+esac
+else
+  sub_bindir=guess
+fi;
+
+if test $sub_bindir = "guess"; then
+  if test $trad_layout = "true"; then
+    sub_bindir=true
+  else
+    sub_bindir=false
+  fi
+fi
+if test $sub_bindir = "true"; then
+  if_enable_sub_bindir=' '
+  if_disable_sub_bindir='#'
+else
+  if_enable_sub_bindir='#'
+  if_disable_sub_bindir=' '
+fi
+
+
+
+# for debug
+echo "$as_me:$LINENO: checking if we use traditional layout" >&5
+echo $ECHO_N "checking if we use traditional layout... $ECHO_C" >&6
+if test $trad_layout = "true"; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+echo "$as_me:$LINENO: checking if we install binaries on \$(bindir)/Wnn4 (etc.)" >&5
+echo $ECHO_N "checking if we install binaries on \$(bindir)/Wnn4 (etc.)... $ECHO_C" >&6
+if test $sub_bindir = "true"; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
 fi
 
 ac_ext=c
@@ -3575,7 +3671,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 3578 "configure"' > conftest.$ac_ext
+  echo '#line 3674 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -4691,7 +4787,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:4694:" \
+echo "$as_me:4790:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -6007,11 +6103,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6010: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6106: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6014: \$? = $ac_status" >&5
+   echo "$as_me:6110: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -6297,11 +6393,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6300: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6396: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6304: \$? = $ac_status" >&5
+   echo "$as_me:6400: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -6401,11 +6497,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6404: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6500: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:6408: \$? = $ac_status" >&5
+   echo "$as_me:6504: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -8687,7 +8783,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8690 "configure"
+#line 8786 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -8787,7 +8883,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8790 "configure"
+#line 8886 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11174,11 +11270,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11177: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11273: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:11181: \$? = $ac_status" >&5
+   echo "$as_me:11277: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -11278,11 +11374,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11281: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11377: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:11285: \$? = $ac_status" >&5
+   echo "$as_me:11381: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -12861,11 +12957,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12864: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12960: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12868: \$? = $ac_status" >&5
+   echo "$as_me:12964: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -12965,11 +13061,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12968: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13064: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12972: \$? = $ac_status" >&5
+   echo "$as_me:13068: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -15153,11 +15249,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15156: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15252: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15160: \$? = $ac_status" >&5
+   echo "$as_me:15256: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -15443,11 +15539,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15446: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15542: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15450: \$? = $ac_status" >&5
+   echo "$as_me:15546: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -15547,11 +15643,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15550: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15646: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:15554: \$? = $ac_status" >&5
+   echo "$as_me:15650: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -21404,6 +21500,9 @@ s,@DEPKWNNJLIB@,$DEPKWNNJLIB,;t t
 s,@KHINSI_DATA@,$KHINSI_DATA,;t t
 s,@ipv6@,$ipv6,;t t
 s,@unsafe_path@,$unsafe_path,;t t
+s,@WNNSBINDIR@,$WNNSBINDIR,;t t
+s,@if_enable_sub_bindir@,$if_enable_sub_bindir,;t t
+s,@if_disable_sub_bindir@,$if_disable_sub_bindir,;t t
 s,@CC@,$CC,;t t
 s,@CFLAGS@,$CFLAGS,;t t
 s,@LDFLAGS@,$LDFLAGS,;t t
